apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-application.fullname" . }}
  labels:
    {{- include "nodejs-application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ printf "http-%d" (int .Values.service.port) }}
  selector:
    {{- include "nodejs-application.selectorLabels" . | nindent 4 }}
